version: '3.9'

name: "realtime-stock-market"

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      stock-net:
        ipv4_address: 172.28.1.1
        
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://172.28.1.2:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      stock-net:
        ipv4_address: 172.28.1.2

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    volumes:
      - ./init-cassandra:/init-cassandra
    environment:
      - CASSANDRA_START_RPC=true
    networks:
      stock-net:
        ipv4_address: 172.28.1.3

  spark:
    image: bitnami/spark:latest
    volumes:
      - ./spark:/opt/bitnami/spark/jobs
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    networks:
      stock-net:
        ipv4_address: 172.28.1.4

networks:
  stock-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
